document.addEventListener('DOMContentLoaded', function () {
  var projects = {
    'meat-sales': { title:'Meat Sales Online Platform', year:'2024', type:'Full stack', client:'Meat Industry Client', duration:'3 months', service:'Full Stack Development', folder:1, count:4, description:'A complete e-commerce experience for a premium meat sales business, designed around clear product discovery and a reliable ordering journey.', features:['Product catalog with quality indicators','Mobile-first responsive design','Real-time product availability updates','Multiple language support','Delivery-zone calculator','Customer reviews, ratings, wishlists and favourites'], tech:['React.js','Node.js','MongoDB','Express.js','Tailwind CSS'] },
    'fish-sales': { title:'Fish Sales Company Website', year:'2024', type:'Frontend', client:'Italian Seafood Company', duration:'2.5 months', service:'Frontend Development', folder:2, count:4, description:'A localised e-commerce platform for fresh Italian seafood, designed to make browsing and ordering feel simple across every screen size.', features:['Fresh seafood catalog with quality indicators','Mobile-first Quasar interface','Italian language localisation','Delivery-zone calculator','Real-time product updates','Reviews, ratings and favourites'], tech:['Vue.js','Quasar','Tailwind CSS','CSS','JavaScript'] },
    'tennis-booking': { title:'Tennis Booking System', year:'2023', type:'Frontend', client:'Tennis Club', duration:'2 months', service:'Frontend Development', folder:3, count:4, description:'A responsive booking experience that helps players see availability, reserve courts, and manage their sessions without friction.', features:['Interactive court-availability calendar','Real-time reservation experience','Booking history and user profiles','Court-management dashboard','Booking email notifications','Weather information for outdoor courts'], tech:['React.js','Redux','Bootstrap','CSS','JavaScript'] },
    'curly-hair': { title:'Curly Hair Salon Website', year:'2023', type:'Frontend', client:'Curly Hair Salon', duration:'1.5 months', service:'Frontend Development', folder:4, count:4, description:'An elegant salon presence focused on showcasing services, stylists and products while creating a clear online booking path.', features:['Service showcase with detailed descriptions','Stylist profiles and specialties','Online appointment booking','Product catalog with reviews','Before-and-after gallery','Testimonials and contact map'], tech:['HTML5','CSS3','JavaScript','jQuery','Bootstrap'] },
    'doctor-website': { title:'Doctor Medical Website', year:'2023', type:'Frontend', client:'Medical Practice', duration:'2 months', service:'Frontend Development', folder:5, count:4, description:'A professional, accessible medical-practice website with patient-friendly navigation, information architecture and appointment-focused flows.', features:['Doctor profiles and specialties','Online appointment scheduling','Patient portal integration','Medical services content','Health resources and blog','Insurance, contact and location details'], tech:['React.js','Tailwind CSS','Firebase','JavaScript','Responsive Design'] },
    'marketing-platform': { title:'E-Selling Marketing Platform', year:'2022', type:'Frontend', client:'Marketing Agency', duration:'3 months', service:'Frontend Development', folder:6, count:5, description:'A marketing platform for e-commerce businesses that brings analytics, customer targeting and campaign management into one usable workspace.', features:['Campaign management dashboard','Customer segmentation tools','Analytics and reporting','Email marketing integration','Social campaign coordination','A/B testing and ROI tracking'], tech:['Next.js','React','Chart.js','Tailwind CSS','TypeScript'] },
    'palmy': { title:'Palmy Fan Engagement', year:'2025', type:'Full stack', client:'Palmy', duration:'1 month', service:'Full Stack Development', folder:7, count:6, description:'A live-event fan engagement product built to turn audience participation into memorable interactive experiences and stronger loyalty.', features:['Real-time fan interaction','Live polls and quizzes','Social media integration','Gamification and rewards','Push notifications','Event-management admin dashboard'], tech:['Nuxt.js','Tailwind CSS','Prisma','Stripe','Socket.io'] },
    'agent-readiness-scanner': { title:'Agent Readiness Scanner', year:'2025', type:'Frontend', client:'Internal Project', duration:'5 days', service:'Frontend Development', folder:8, count:9, description:'An AI optimisation scanner that helps teams understand how clearly their pages can be discovered and interpreted by modern AI agents.', features:['AI readiness analysis','Actionable optimisation insights','Multi-agent coverage','Clear reporting interface','Secure Clerk authentication','Stripe subscriptions'], tech:['React.js','Vite','Tailwind CSS','Vercel','Stripe','Chart.js','Clerk'] },
    'air-connect': { title:'Air Connect', year:'2025', type:'Full stack', client:'Air University Multan Campus', duration:'1.5 months', service:'Full Stack Development', folder:9, count:25, description:'A MERN facilitation portal for Air University Multan Campus, connecting students, teachers, coordinators and student affairs in synchronised workflows.', features:['Four role-specific portals','Synchronized student, teacher and coordinator data','Real-time Socket.io chat','Nodemailer email notifications','React Hook Form and Zod validation','Shadcn UI and Tailwind interface','MongoDB data management'], tech:['React.js','Node.js','MongoDB','Express.js','Tailwind CSS','Socket.io','Nodemailer','Shadcn UI','Zod'] }
  };
  var id = new URLSearchParams(window.location.search).get('id');
  var project = projects[id];
  var target = document.getElementById('projectDetail');
  if (!project) { target.innerHTML = '<section class="pd-hero"><div class="wrap"><a href="index.html#projects" class="back">&larr; All projects</a><h1>Project not found.</h1></div></section>'; return; }
  document.title = project.title + ' | Muhammad Bilal';
  var images = []; for (var i = 1; i <= project.count; i++) images.push('assets/projects/project-' + project.folder + '/image-' + i + '.webp');
  target.innerHTML = '<section class="pd-hero"><div class="wrap"><a href="index.html#projects" class="back">&larr; All projects</a><div class="kicker">' + project.year + ' &middot; ' + project.type + '</div><h1>' + project.title + '</h1><p class="tagline">' + project.description + '</p><div class="pd-meta"><div class="cell"><div class="k">client</div><div class="v">' + project.client + '</div></div><div class="cell"><div class="k">service</div><div class="v">' + project.service + '</div></div><div class="cell"><div class="k">duration</div><div class="v">' + project.duration + '</div></div><div class="cell"><div class="k">year</div><div class="v">' + project.year + '</div></div></div></div></section><section class="pd-gallery"><div class="wrap"><img class="pd-cover" src="' + images[0] + '" alt="' + project.title + ' project screenshot"><div class="pd-gallery-grid">' + images.slice(1).map(function (image, index) { return '<img src="' + image + '" alt="' + project.title + ' screenshot ' + (index + 2) + '" loading="lazy">'; }).join('') + '</div></div></section><section class="pd-body"><div class="wrap cols"><div class="pd-block"><h3>Project overview</h3><p>' + project.description + '</p><h3>What I delivered</h3><ul>' + project.features.map(function (feature) { return '<li>' + feature + '</li>'; }).join('') + '</ul></div><div class="pd-block"><h3>Technology</h3><div class="pd-tech">' + project.tech.map(function (tech) { return '<span>' + tech + '</span>'; }).join('') + '</div><h3>Approach</h3><p>The implementation focused on a polished responsive interface, clear task flows, and a build that is practical for the team maintaining it after launch.</p></div></div></section><section class="pd-cta"><div class="wrap"><div class="box"><div><h3>Have a project in mind?</h3><p>Let’s build a fast, useful product with a strong interface.</p></div><a href="mailto:muhammadbilaltoor7@gmail.com" class="btn btn-primary">Get in touch</a></div></div></section>';
  var y = document.querySelector('[data-year]'); if (y) y.textContent = new Date().getFullYear();
});
